# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup},.
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }]},
#   Mayor.create(name: 'Emanuel', city: cities.first},
# Jigu.create([
#     { name: 'jongro'},
#     { name: 'junggu'},
#     { name: 'yongsan'},
#     { name: 'sungdong'},
#     { name: 'gwangjin'},
#     { name: 'dongdaemoon'},
#     { name: 'jungrang'},
#     { name: 'sungbuk'},
#     { name: 'gangbuk'},
#     { name: 'dobong'},
#     { name: 'nowon'},
#     { name: 'enpung'},
#     { name: 'seodaemoon'},
#     { name: 'mapo'},
#     { name: 'yangcheon'},
#     { name: 'gangseo'},
#     { name: 'guro'},
#     { name: 'gumcheon'},
#     { name: 'yungdeongpo'},
#     { name: 'dongjak'},
#     { name: 'gwanak'},
#     { name: 'seocho'},
#     { name: 'gangnam'},
#     { name: 'songpa'},
#     { name: 'gangdong'}
    
#     ]},
Jigu.create([
    { name: 'cb_1'},
    { name: 'cb_2'},
    { name: 'cn_1'},
    { name: 'cn_2'},
    { name: 'cn_3'},
    { name: 'jeju'},
    { name: 'jb_1'},
    { name: 'jb_2'},
    { name: 'jn_1'},
    { name: 'jn_2'},
    { name: 'jn_3'},
    { name: 'ulsan'},
    { name: 'sejong'},
    { name: 'busan'},
    { name: 'daejeon'},
    { name: 'daegu'},
    { name: 'gwangju'},
    { name: 'kb_1'},
    { name: 'kb_2'},
    { name: 'kb_3'},
    { name: 'kn_1'},
    { name: 'kn_2'},
    { name: 'kw_1'},
    { name: 'kw_2'},
    { name: 'sudo_1'},
    { name: 'sudo_2'},
    { name: 'sudo_3'},
    { name: 'sudo_4'},
    { name: 'sudo_5'},
    { name: 'sudo_6'},
    { name: 'sudo_7'},
    { name: 'sudo_8'},
    { name: 'sudo_9'},
    { name: 'sudo_10'}
    ])


Event.create([    
{name: "헬스"},
{name: "G.X"}, 
{name: "P.T"}, 
{name: "골프"}, 
{name: "요가"}, 
{name: "필라테스"}, 
{name: "수영"}, 
{name: "스쿼시"}, 
{name: "에어로빅"}, 
{name: "스크린골프"}, 
{name: "사우나"}, 
{name: "찜질방"}, 
{name: "스피닝"}, 
{name: "크로스핏"}, 
{name: "복싱"}, 
{name: "마사지"}, 
{name: "댄스"}, 
{name: "탁구"}, 
{name: "야구"}, 
{name: "검도"}, 
{name: "클라이밍"}, 
{name: "킥복싱"}, 
{name: "격투기"}, 
{name: "순환운동"}, 
{name: "플라잉요가"}, 
{name: "폴댄스"}, 
{name: "네일"}, 
{name: "뷰티"}, 
{name: "기타"}
])